# Generated by Django 3.2.25 on 2026-01-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0002_auto_20260125_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='status',
            field=models.CharField(choices=[('pending', 'In Attesa'), ('approved', 'Approvato'), ('rejected', 'Rifiutato')], default='pending', max_length=10),
        ),
    ]
